# Generated by Django 4.1.4 on 2022-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favorite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
