# Generated by Django 4.1.4 on 2022-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_category_description_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
