"""empty message

Revision ID: 19a8c40f8d8b
Revises: 965a9c3e2199
Create Date: 2022-05-03 14:09:35.696652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a8c40f8d8b'
down_revision = '965a9c3e2199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickers_tickername', table_name='tickers')
    op.create_index(op.f('ix_tickers_tickername'), 'tickers', ['tickername'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_tickername'), table_name='tickers')
    op.create_index('ix_tickers_tickername', 'tickers', ['tickername'], unique=False)
    # ### end Alembic commands ###
