"""Market

Revision ID: 2e8bc83dd23b
Revises: 
Create Date: 2022-04-28 14:32:22.836717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8bc83dd23b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trickername', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_cost'), 'tickers', ['cost'], unique=True)
    op.create_index(op.f('ix_tickers_trickername'), 'tickers', ['trickername'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_trickername'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_cost'), table_name='tickers')
    op.drop_table('tickers')
    # ### end Alembic commands ###
