"""empty message

Revision ID: 884d715b8fff
Revises: dcd7cd86fad6
Create Date: 2022-05-03 13:31:47.200686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884d715b8fff'
down_revision = 'dcd7cd86fad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('сreated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('tickers', 'dateCreated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('dateCreated', sa.DATETIME(), nullable=True))
    op.drop_column('tickers', 'сreated')
    # ### end Alembic commands ###
