"""Market

Revision ID: ccfea89a0dc8
Revises: 2e8bc83dd23b
Create Date: 2022-04-28 14:59:31.785967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfea89a0dc8'
down_revision = '2e8bc83dd23b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('tickername', sa.String(length=10), nullable=True))
    op.drop_index('ix_tickers_trickername', table_name='tickers')
    op.drop_index('ix_tickers_cost', table_name='tickers')
    op.create_index(op.f('ix_tickers_cost'), 'tickers', ['cost'], unique=False)
    op.create_index(op.f('ix_tickers_tickername'), 'tickers', ['tickername'], unique=True)
    op.drop_column('tickers', 'trickername')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('trickername', sa.VARCHAR(length=10), nullable=True))
    op.drop_index(op.f('ix_tickers_tickername'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_cost'), table_name='tickers')
    op.create_index('ix_tickers_cost', 'tickers', ['cost'], unique=False)
    op.create_index('ix_tickers_trickername', 'tickers', ['trickername'], unique=False)
    op.drop_column('tickers', 'tickername')
    # ### end Alembic commands ###
